### PR TITLE
Fix offsetDifference and scaleDifference

### PR DESCRIPTION
**Pull request by occamsystems**
Offset difference and scale difference no longer throw exceptions when the provided Units do not have explicit conversion values

Instead, the unchecked get() are replaced by orElse() calls, providing the correct default values.

This fixes a bug when, for example, trying to find the offsetDifference between Inch and Meter, which do not bother to specify their 0 offsets explicitly.

### CODE REVIEW

**Review by fkleedorfer — CHANGES_REQUESTED** [review]
Thank you very much for your contribution!!

That looks simple enough, but it's only half the fix: the bug was not discovered by our tests, so we need a test that reproduces the bug. Can you please add one to qudtlib-test/src/test/java/io/github/qudtlib/QudtTests.java? Thanks!

**Comment by occamsystems** [comment]
I added a test here. For some reason, directly running the QudtTests does not work for me. (Neither using IntelliJ built-in test runner, nor using the maven test target.) I would somewhat prefer to validate that corresponding unit has a specific value in the test, but really the main thing is that it shouldn't throw an exception.

**Comment by occamsystems** [comment]
Adding the jar dependency in my ij module did it. I added a more specific check, now that I know it will actually pass.

**Comment by fkleedorfer** [comment]
ok, thank you!
Can you synchronize your fork and rebase onto main, please?

**Comment by occamsystems** [comment]
Synched my fork. Merge should now be clean.

**Comment by fkleedorfer** [comment]
`mvn install` fails because the source of Qudt.java does not pass the spotless checks. 
Please run `mvn spotless:apply` at the top level and push again

**Comment by fkleedorfer** [comment]
hm. not sure. I'll deal with it then.

**Comment by fkleedorfer** [comment]
Thanks again!

**Comment by fkleedorfer** [comment]
The fix is in bugfix release 6.0.3

**Pull request merged**
